In [87]:
%matplotlib qt

import neuroseries as nts

import numpy as np
import matplotlib.pyplot as plt
import scipy.stats
import scipy.ndimage
import os

import scipy.signal
import scipy.stats

import bk.load as bk
import bk.plot
import bk.compute

def TTLtoTimes(TTL,Fs = 20000):
    
    if isinstance(TTL[0],(np.bool_,bool)):
        TTL = list(map(int,TTL))
    
    diff_TTL = np.diff(TTL)
    
    t_start = np.where(diff_TTL == 1)
    t_end = np.where(diff_TTL == -1)
    t_TTL = np.array([np.mean(interval,0) for interval in zip(t_start,t_end)])[0]
    
    return t_TTL/Fs

def speed(pos):
    
    x_speed = np.diff(pos['x'])/np.diff(pos.index)
    y_speed = np.diff(pos['y'])/np.diff(pos.index)
    
    v = np.sqrt(x_speed**2 + y_speed**2)
    
    return v

def load_pos():
    import pandas as pd
    files = os.listdir()
    for f in files: 
        if f.endswith('.h5'): 
            filename = f
    
    data = pd.read_hdf(filename)
    data = data[data.keys()[0][0]]
    return data

def load_digitalin(channels,Fs = 20000):
    import pandas as pd
    
    digital_word = np.fromfile('digitalin.dat','uint16')
    sample = len(digital_word)
    time = np.arange(0,sample)
    time = time/Fs

    chan = {}
    
    for i in range(len(channels)):
        chan.update({channels[i]:(digital_word & 2**i)>0})

    return time,chan



In [3]:
path = 'Y:/ExampleSession/rat01_200630_114732'
path = 'Y:/ExampleSession/rat01_200630_171900'
path = 'Y:/ExampleSession/rat01_200630_183149/'

path = 'Y:/ExampleSession/RAT02/rat02_200707_114611'


i = 1
title = ['Fear','Tone','Context']

os.chdir(path)
step = 1

time,data = load_digitalin(['TTL','Shock','Tone'])
pos = load_pos()

s = speed(pos['snout'])
s = scipy.ndimage.gaussian_filter1d(s,1)

tf = TTLtoTimes(data['TTL'])
tf = np.delete(tf,-1)

pos.index = tf
time = time[0:-1:step]

fig = plt.subplot(1,1,i)
plt.tight_layout()
plt.title(title[i-1])
plt.plot(time,data['TTL'][0:-1:step])
plt.plot(time,data['Shock'][0:-1:step] * 3)
plt.plot(time,data['Tone'][0:-1:step]*2)
plt.plot(pos.index[:-1],s/15)
plt.legend(['TTL','Shock','Tone','Speed'])wo
plt.xlabel('Time (s)')
#plt.vlines(x=tf,ymin = 0, ymax = 3,color='red')
i += 1

plt.show()

In [3]:
path = '/media/billel/DATA/ExampleSession/RAT01/'
subpath = os.listdir(path)

In [111]:
i = 1
title = ['Fear','Tone','Context']


os.chdir(os.path.join(path,subpath[1]))
step = 20





time,data = load_digitalin(['TTL','Shock','Tone'])
pos = load_pos()

s = speed(pos['snout'])
s = scipy.ndimage.gaussian_filter1d(s,1)
s = nts.Tsd(pos.index.values[:-1],s)





tf = TTLtoTimes(data['TTL'])
tf = np.delete(tf,-1)

pos.index = tf
fs_video = 1/scipy.stats.mode(np.diff(pos.index)).mode[0]

time = time[0:-1:step]

fig = plt.subplot(1,1,i)
plt.tight_layout()
plt.title(title[i-1])
plt.plot(time,data['TTL'][0:-1:step])
plt.plot(time,data['Shock'][0:-1:step] * 3)
plt.plot(time,data['Tone'][0:-1:step]*2)
plt.plot(pos.index[:-1],s.values/15)
plt.legend(['TTL','Shock','Tone','Speed'])
plt.xlabel('Time (s)')
#plt.vlines(x=tf,ymin = 0, ymax = 3,color='red')
i += 1

bk.plot.intervals(bk.compute.freezing(s,1),col='orange')
plt.show()


NameError: name 'pos' is not defined

In [104]:

s.as_units('s')

Time (s)
0.000000   NaN
0.000001   NaN
0.000002   NaN
0.000003   NaN
0.000004   NaN
            ..
0.018674   NaN
0.018675   NaN
0.018676   NaN
0.018677   NaN
0.018678   NaN
Length: 18679, dtype: float64

In [100]:
T = 10
l_s = np.int8(s<T)

TypeError: __init__() got multiple values for keyword argument 'index'

In [93]:
s

array([ 8.97745321, 37.26218868, 69.86626172, ...,  0.34334132,
        0.4637236 ,  0.52487631])

array([ 8, 37, 69, ...,  0,  0,  0], dtype=uint64)

In [53]:
np.where([True,True,False,True,False])

(array([0, 1, 3]),)

In [59]:
t_start = [1,2,3,4]
t_end = [2,3,4,5]



np.array([np.mean(interval) for interval in zip(t_start,t_end)])

array([1.5, 2.5, 3.5, 4.5])

In [60]:
bk.load.pos

<function bk.load.pos()>

In [83]:
freezing(s,5).as_units('s')

start         end
0      8.752599    9.285799
1      9.918974   10.085599
2     10.718774   10.818749
3     11.585224   11.618549
4     11.951799   12.518324
..          ...         ...
152  173.877974  174.877724
153  174.977699  175.011024
154  175.144324  175.210974
155  175.310949  175.810824
156  176.310699  630.697074

[157 rows x 2 columns]