In [1]:
import bk.load
import scipy.io
import numpy as np
import pandas as pd
import os

In [2]:
def makeRegionTypes(path):
    
    bk.load.current_session(path)
    neurons,shanks = bk.load.loadSpikeData(bk.load.path)
    
    finalType = scipy.io.loadmat('Z:\All-Rats\AllRats-FinalType.mat')['finalType']
    finalType = finalType[np.all(finalType[:,0:2]==[bk.load.rat,bk.load.day],1)]
    
    types = np.empty((shanks.shape[0],1),dtype = np.object)
    types[finalType[:,4] == 0] = 'Unk'
    types[finalType[:,4] == 1] = 'Pyr'
    types[finalType[:,4] == 2] = 'Int'
    
    structures = scipy.io.loadmat('Z:\All-Rats\Structures\structures.mat')
    useless  = ['__header__','__version__','__globals__','olfact','basal']
    for u in useless:
        del structures[u]
         
    for s in structures:
        structures[s] = structures[s][np.all(structures[s][:,0:2] == [bk.load.rat,bk.load.day],1),:]
    
    stru = []
    for sh in shanks[:,0]:
        for st in structures:
            if np.any(structures[st]):
                if sh in structures[st][:,2]:
                    stru.append([st])
                    break
        else: stru.append(['None'])
                    
    metadata = np.hstack((shanks,stru,types))
    metadata = pd.DataFrame(metadata,columns=['Shank','Id','Region','Type'])
    
    print('Saving metadata for ' + str(len(metadata)) + ' neurons as ' + bk.load.session+'-metadata')
    np.save(bk.load.session+'-metadata',metadata)
    
    print('Deleting '+bk.load.session+'-neuronsShanks.npy')
    os.remove(bk.load.session + '-neuronsShanks.npy')

In [19]:
path = 'Z:\Rat08\Rat08-20130722'
bk.load.current_session(path)
%debug makeRegionTypes(path)

Rat : 8 on day : 13
Working with session Rat08-20130722 @ Z:\Rat08\Rat08-20130722
NOTE: Enter 'c' at the ipdb>  prompt to continue execution.
> <string>(1)<module>()



ipdb>  c


Rat : 8 on day : 13
Working with session Rat08-20130722 @ Z:\Rat08\Rat08-20130722
Loading Rat08-20130722.clu.5
Loading Rat08-20130722.clu.6
Loading Rat08-20130722.clu.7
Loading Rat08-20130722.clu.8
Loading Rat08-20130722.clu.9
Loading Rat08-20130722.clu.10
Loading Rat08-20130722.clu.11
Loading Rat08-20130722.clu.12
Loading Rat08-20130722.clu.13
Loading Rat08-20130722.clu.14
Loading Rat08-20130722.clu.15
Loading Rat08-20130722.clu.16
Loading Rat08-20130722.clu.17
Loading Rat08-20130722.clu.18
Loading Rat08-20130722.clu.19
Loading Rat08-20130722.clu.20

Saving data in Numpy format :
Saving Rat08-20130722-neurons.npy
Saving Rat08-20130722-neuronsShanks.npy
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-2-fdebf48ac198> in makeRegionTypes(path)
      8 
      9     types = np.empty((shanks.shape[0],1),dtype = np.object)
---> 10     types[finalType[:,4] == 0] = 'Unk'
     1

In [176]:
bk.load.batch(makeRegionTypes)

Batch finished in 4.597650051116943
Some session were not processed correctly
['Rat08-20130708', 'Rat08-20130709', 'Rat08-20130710', 'Rat08-20130711', 'Rat08-20130712', 'Rat08-20130713', 'Rat08-20130715', 'Rat08-20130716', 'Rat08-20130717', 'Rat08-20130718', 'Rat08-20130719', 'Rat08-20130720', 'Rat08-20130722', 'Rat09-20140324', 'Rat09-20140325', 'Rat09-20140326', 'Rat09-20140327', 'Rat09-20140328', 'Rat09-20140329', 'Rat09-20140331', 'Rat09-20140401', 'Rat09-20140402', 'Rat09-20140403', 'Rat09-20140404', 'Rat09-20140405', 'Rat09-20140407', 'Rat09-20140408', 'Rat09-20140409', 'Rat10-20140619', 'Rat10-20140620', 'Rat10-20140622', 'Rat10-20140624', 'Rat10-20140626', 'Rat10-20140627', 'Rat10-20140628', 'Rat10-20140629', 'Rat10-20140701', 'Rat10-20140702', 'Rat10-20140703', 'Rat10-20140704', 'Rat10-20140705', 'Rat10-20140707', 'Rat10-20140708', 'Rat11-20150310', 'Rat11-20150312', 'Rat11-20150313', 'Rat11-20150314', 'Rat11-20150315', 'Rat11-20150316', 'Rat11-20150317', 'Rat11-20150321', 'Ra

{}

In [20]:
bk.load.current_session(path)
neurons,shanks = bk.load.loadSpikeData(bk.load.path)

finalType = scipy.io.loadmat('Z:\All-Rats\AllRats-FinalType.mat')['finalType']
finalType = finalType[np.all(finalType[:,0:2]==[bk.load.rat,bk.load.day],1)]

types = np.empty((shanks.shape[0],1),dtype = np.object)
types[finalType[:,4] == 0] = 'Unk'
types[finalType[:,4] == 1] = 'Pyr'
types[finalType[:,4] == 2] = 'Int'

structures = scipy.io.loadmat('Z:\All-Rats\Structures\structures.mat')
useless  = ['__header__','__version__','__globals__','olfact','basal']
for u in useless:
    del structures[u]

for s in structures:
    structures[s] = structures[s][np.all(structures[s][:,0:2] == [bk.load.rat,bk.load.day],1),:]

stru = []
for sh in shanks[:,0]:
    for st in structures:
        if np.any(structures[st]):
            if sh in structures[st][:,2]:
                stru.append([st])
                break
    else: stru.append(['None'])


metadata = np.hstack((shanks,stru,types))
metadata = pd.DataFrame(metadata,columns=['Shank','Id','Region','Type'])

print('Saving metadata for ' + str(len(metadata)) + ' neurons as ' + bk.load.session+'-metadata')
np.save(bk.load.session+'-metadata',metadata)
print('Deleting '+bk.load.session+'-neuronsShanks.npy')

os.remove(bk.load.session + '-neuronsShanks.npy')

Rat : 8 on day : 13
Working with session Rat08-20130722 @ Z:\Rat08\Rat08-20130722
Loading Rat08-20130722.clu.5
Loading Rat08-20130722.clu.6
Loading Rat08-20130722.clu.7
Loading Rat08-20130722.clu.8
Loading Rat08-20130722.clu.9
Loading Rat08-20130722.clu.10
Loading Rat08-20130722.clu.11
Loading Rat08-20130722.clu.12
Loading Rat08-20130722.clu.13
Loading Rat08-20130722.clu.14
Loading Rat08-20130722.clu.15
Loading Rat08-20130722.clu.16
Loading Rat08-20130722.clu.17
Loading Rat08-20130722.clu.18
Loading Rat08-20130722.clu.19
Loading Rat08-20130722.clu.20

Saving data in Numpy format :
Saving Rat08-20130722-neurons.npy
Saving Rat08-20130722-neuronsShanks.npy


IndexError: boolean index did not match indexed array along dimension 0; dimension is 152 but corresponding boolean dimension is 127

In [39]:
shanks[shanks[:,0] == 6]

array([[ 6,  2],
       [ 6,  3],
       [ 6,  4],
       [ 6,  5],
       [ 6,  6],
       [ 6,  7],
       [ 6,  8],
       [ 6,  9],
       [ 6, 10],
       [ 6, 11]], dtype=int64)

In [40]:
neurons

TypeError: __init__() got multiple values for keyword argument 'index'

In [38]:
finalType[finalType[:,2] == 6]

array([[ 8, 13,  6,  2,  1],
       [ 8, 13,  6,  3,  2],
       [ 8, 13,  6,  4,  1],
       [ 8, 13,  6,  5,  1],
       [ 8, 13,  6,  6,  1],
       [ 8, 13,  6,  7,  1],
       [ 8, 13,  6,  8,  1],
       [ 8, 13,  6,  9,  1]], dtype=uint8)

In [104]:
structures = scipy.io.loadmat('Z:\All-Rats\Structures\structures.mat')
useless  = ['__header__','__version__','__globals__','basal','olfact']
for u in useless:
    del structures[u]
for s in structures:
    structures[s] = structures[s][np.all(structures[s][:,0:2] == [bk.load.rat,bk.load.day],1),:]
    
for s in structures:
    if np.any(structures[s]): print(s+str(structures[s][:,2]))

BLA[7]
CeCM[ 5  6 13 14 15]
DEn[10 11]
Hpc[1 2 3 4]
LaDL[ 8  9 17 18 19]
Pir[12]


In [123]:
metadata

array([[1, 2, 'Hpc', 'Pyr', 'Hpc', 'Pyr'],
       [2, 2, 'Hpc', 'Pyr', 'Hpc', 'Pyr'],
       [2, 3, 'Hpc', 'Pyr', 'Hpc', 'Pyr'],
       ...,
       [19, 4, 'BLA', 'Pyr', 'BLA', 'Pyr'],
       [19, 5, 'BLA', 'Pyr', 'BLA', 'Pyr'],
       [19, 6, 'BLA', 'Pyr', 'BLA', 'Pyr']], dtype=object)

In [75]:
np.unique(shanks[:,0])

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20], dtype=int64)

[ 5  6  7  8 16 17 18 19]
[13 14 15]
[ 9 10 11 20]
[1 2 3 4]
[12]
[ 5  6  7  8 16 17 18 19]
[12  9 10 11 20]


In [138]:
for i in range(10):
    if i%2 == 0:
        print('hey')
else: print('jp')

hey
hey
hey
hey
hey
jp


In [144]:
def l(path):
    bk.load.current_session(path)
    m = np.load(bk.load.session+'-metadata.npy',allow_pickle=True)
    return m

In [146]:
a = bk.load.batch(l)

Batch finished in 0.25281453132629395
Some session were not processed correctly
['Rat08-20130722']
1.639344262295082 %


In [147]:
a['Rat09-20140405']

array([[1, 2, 'Pir', 'Pyr'],
       [1, 3, 'Pir', 'Int'],
       [1, 4, 'Pir', 'Pyr'],
       [1, 5, 'Pir', 'Pyr'],
       [2, 2, 'Pir', 'Pyr'],
       [2, 3, 'Pir', 'Pyr'],
       [2, 4, 'Pir', 'Pyr'],
       [2, 5, 'Pir', 'Pyr'],
       [2, 6, 'Pir', 'Pyr'],
       [2, 7, 'Pir', 'Pyr'],
       [2, 8, 'Pir', 'Pyr'],
       [2, 9, 'Pir', 'Pyr'],
       [3, 2, 'Pir', 'Pyr'],
       [3, 3, 'Pir', 'Pyr'],
       [3, 4, 'Pir', 'Pyr'],
       [3, 5, 'Pir', 'Pyr'],
       [4, 2, 'Pir', 'Int'],
       [4, 3, 'Pir', 'Pyr'],
       [4, 4, 'Pir', 'Pyr'],
       [4, 5, 'Pir', 'Pyr'],
       [4, 6, 'Pir', 'Pyr'],
       [4, 7, 'Pir', 'Pyr'],
       [4, 8, 'Pir', 'Pyr'],
       [5, 2, 'Pir', 'Pyr'],
       [5, 3, 'Pir', 'Pyr'],
       [5, 4, 'Pir', 'Pyr'],
       [5, 5, 'Pir', 'Int'],
       [5, 6, 'Pir', 'Int'],
       [6, 2, 'Pir', 'Pyr'],
       [6, 3, 'Pir', 'Pyr'],
       [6, 4, 'Pir', 'Pyr'],
       [6, 5, 'Pir', 'Int'],
       [7, 2, 'Pir', 'Pyr'],
       [7, 3, 'Pir', 'Pyr'],
       [7, 4, 

In [154]:
d = pd.DataFrame(np.random.rand(5,5),columns=['a','b','c','d','d'])

In [152]:
os.chdir('z:\Python\Billel')

In [172]:
np.save('hey',d,allow_pickle=True)

In [173]:
a = np.load('hey.npy')

In [174]:
d

a         b         c         d         d
0  0.463819  0.403983  0.235225  0.241080  0.915925
1  0.431776  0.572917  0.391561  0.855457  0.492264
2  0.362837  0.842247  0.363421  0.443556  0.842167
3  0.064445  0.778700  0.954831  0.132383  0.314215
4  0.608921  0.435984  0.281913  0.001495  0.185207

In [175]:
a

array([[0.4638195 , 0.40398263, 0.23522491, 0.2410797 , 0.915925  ],
       [0.43177558, 0.57291706, 0.3915606 , 0.85545651, 0.49226401],
       [0.36283696, 0.84224736, 0.36342138, 0.44355559, 0.84216724],
       [0.06444506, 0.77869983, 0.95483084, 0.13238335, 0.3142153 ],
       [0.60892116, 0.43598425, 0.28191254, 0.00149543, 0.18520704]])