# Histogram of power of theta in BLA during REM

In [1]:
import os

import bk.load
import bk.compute
import bk.plot
import bk.signal

import numpy as np

import scipy.signal
import scipy.stats
import scipy.io

import matplotlib.pyplot as plt
import matplotlib as mpl
import neuroseries as nts

import pycorrelate

import basefunction.pdc_tdf as pdc_tdf

In [57]:
def plot_phase_shift(path):
    
#     bk.load.current_session(path)
    states = bk.load.states()
    run = scipy.io.loadmat(bk.load.session + '-TrackRunTimes.mat')['trackruntimes']
    run = nts.IntervalSet(run[:,0],run[:,1],time_units='s')
    theta = {'Rem':states['Rem'],'run':run,'wake':states['wake']}
    
    
    nchannels = 166
    
    bla = 105
    hpc = 1
    
    plt.figure()
    plt.suptitle(f'Theta PhaseShift in session {bk.load.session}')
    for i,state in enumerate(theta,1):
        lfp_hpc = bk.load.lfp_in_intervals(nchannels,hpc,theta[state])
        lfp_bla = bk.load.lfp_in_intervals(nchannels,bla,theta[state])

        filt_hpc = bk.signal.passband(lfp_hpc,4,8)
        filt_bla = bk.signal.passband(lfp_bla,4,8)

        power_hpc,phase_hpc = bk.signal.hilbert(filt_hpc,deg = True)
        power_bla,phase_bla = bk.signal.hilbert(filt_bla,deg = True)

        plt.subplot(3,1,i)
        plt.hist2d(phase_hpc.values+180,phase_bla.values+180,100)
        plt.title(f'Theta Phase shift during {state}')
        plt.xlabel('hpc_phase')
        plt.ylabel('bla_phase')

        # plt.figure()
    # plt.suptitle('Spectrograms')
plot_phase_shift(bk.load.path)

In [ ]:
 for i,state in enumerate(theta,4):

        lfp_hpc = bk.load.lfp_in_intervals(nchannels,hpc,theta[state])
        lfp_bla = bk.load.lfp_in_intervals(nchannels,bla,theta[state])

        f,spec_hpc = scipy.signal.welch(lfp_hpc,fs = 1250,nperseg=10000,noverlap=9000)
        f,spec_bla = scipy.signal.welch(lfp_bla,fs = 1250,nperseg=10000,noverlap=9000)

        plt.subplot(3,3,i)
        plt.title(f'Power Spectrum during {state}')
        plt.plot(f,spec_hpc)
        plt.plot(f,spec_bla)
        plt.xlim(0,100)
        plt.yscale('log')
        plt.legend(['Hpc','BLA'])
        
    for i,state in enumerate(theta,7):
        lfp_hpc = bk.load.lfp_in_intervals(nchannels,hpc,theta[state])
        lfp_bla = bk.load.lfp_in_intervals(nchannels,bla,theta[state])
        
        t = np.linspace(-1,1,2500)
        xcorrpos =  pycorrelate.ucorrelate(lfp_hpc.values-np.mean(lfp_hpc.values),lfp_bla.values-np.mean(lfp_bla.values),maxlag= 1250)
        xcorrneg =  pycorrelate.ucorrelate(lfp_bla.values-np.mean(lfp_bla.values),lfp_hpc.values-np.mean(lfp_hpc.values),maxlag= 1250)
        plt.subplot(3,3,i)
        plt.title(f'Cross-corr of RAW Lfp during {state}')
        plt.plot(t,np.hstack((xcorrneg[::-1],xcorrpos)))

In [41]:
%matplotlib qt

In [48]:
COLOR = 'white'
mpl.rcParams['text.color'] = COLOR
mpl.rcParams['axes.labelcolor'] = COLOR
mpl.rcParams['axes.edgecolor'] = COLOR
mpl.rcParams['xtick.color'] = COLOR
mpl.rcParams['ytick.color'] = COLOR
mpl.rcParams['figure.facecolor'] = '#282C34'
mpl.rcParams['axes.facecolor'] = '#282C34'

In [49]:
path = '/media/billel/GGLab-01-BK/DATA/Rat08-20130713/'
os.chdir(path)
bk.load.path = path
bk.load.rat = 8
bk.load.session = 'Rat08-20130713'
bk.load.day = 6

In [24]:
bk.load.current_session()

FileNotFoundError: [Errno 2] No such file or directory: 'Z:/All-Rats/Billel/session_indexing.csv'

In [45]:
neurons,metadata = bk.load.loadSpikeData(bk.load.path)

Data already saved in Numpy format, loading them from here:
Rat08-20130713-neurons.npy
Rat08-20130713-metadata.npy


In [46]:
metadata

Rat Day Shank Id Region Type
0     8   6     1  2    Hpc  Pyr
1     8   6     2  2    Hpc  Pyr
2     8   6     2  3    Hpc  Pyr
3     8   6     2  4    Hpc  Pyr
4     8   6     2  5    Hpc  Pyr
..   ..  ..   ... ..    ...  ...
247   8   6    19  2    BLA  Pyr
248   8   6    19  3    BLA  Pyr
249   8   6    19  4    BLA  Pyr
250   8   6    19  5    BLA  Pyr
251   8   6    19  6    BLA  Pyr

[252 rows x 6 columns]

In [50]:
plot_phase_shift(bk.load.path)

In [25]:
states = bk.load.states()

In [7]:
nch = 166
hpc = 23
bla = 105

lfp_hpc = bk.load.lfp_in_intervals(nch,hpc,states['Rem'])
lfp_bla = bk.load.lfp_in_intervals(nch,bla,states['Rem'])

In [8]:
fit = pdc_tdf.mvar_fit(np.array((lfp_hpc.values,lfp_bla.values)),2500)

In [13]:
pdc,f = pdc_tdf.DTF(fit[0])

In [14]:
pdc_tdf.plot_all(f,pdc,'hey')

In [ ]:
scipy.signal.butter()

In [18]:
sessions = bk.load.sessions()
sessions = sessions[sessions['Rat'] == 8]

for s in sessions['Path']:
    plot_phase_shift(s)

Rat : 8 on day : 1
Working with session Rat08-20130708 @ Z:\Rat08\Rat08-20130708
Rat : 8 on day : 2
Working with session Rat08-20130709 @ Z:\Rat08\Rat08-20130709
Rat : 8 on day : 3
Working with session Rat08-20130710 @ Z:\Rat08\Rat08-20130710
Rat : 8 on day : 4
Working with session Rat08-20130711 @ Z:\Rat08\Rat08-20130711
Rat : 8 on day : 5
Working with session Rat08-20130712 @ Z:\Rat08\Rat08-20130712
Rat : 8 on day : 6
Working with session Rat08-20130713 @ Z:\Rat08\Rat08-20130713
Rat : 8 on day : 7
Working with session Rat08-20130715 @ Z:\Rat08\Rat08-20130715
Rat : 8 on day : 8
Working with session Rat08-20130716 @ Z:\Rat08\Rat08-20130716
Rat : 8 on day : 9
Working with session Rat08-20130717 @ Z:\Rat08\Rat08-20130717
Rat : 8 on day : 10
Working with session Rat08-20130718 @ Z:\Rat08\Rat08-20130718
Rat : 8 on day : 11
Working with session Rat08-20130719 @ Z:\Rat08\Rat08-20130719
Rat : 8 on day : 12
Working with session Rat08-20130720 @ Z:\Rat08\Rat08-20130720


FileNotFoundError: [Errno 2] No such file or directory: 'Z:\\Rat08\\Rat08-20130720/States.mat'

In [110]:


path = bk.load.path
states = bk.load.states()
run = scipy.io.loadmat(bk.load.session + '-TrackRunTimes.mat')['trackruntimes']
run = nts.IntervalSet(run[:,0],run[:,1],time_units='s')
theta = {'Rem':states['Rem'],'run':run,'wake':states['wake']}

Rat : 8 on day : 10
Working with session Rat08-20130718 @ Z:\Rat08\Rat08-20130718


In [15]:
bk.load.current_session('Z:\Rat08\Rat08-20130715')
plot_phase_shift(bk.load.path)

Rat : 8 on day : 7
Working with session Rat08-20130715 @ Z:\Rat08\Rat08-20130715
Rat : 8 on day : 7
Working with session Rat08-20130715 @ Z:\Rat08\Rat08-20130715


In [93]:
plt.figure()
plt.suptitle(bk.load.session)


plt.subplot(1,2,1)
plt.title('REM')
stru = {'hpc':13,'BLA':105}
lfp = {}
for s,c in zip(stru.keys(),stru.values()):
    print(s,c)
    lfp.update({s:bk.load.lfp_in_intervals(166,c,theta['Rem'])})
xcorrpos = pycorrelate.ucorrelate(lfp['hpc'].values,lfp['BLA'].values,maxlag= 1250)
xcorrneg =  pycorrelate.ucorrelate(lfp['BLA'].values,lfp['hpc'].values,maxlag= 1250)
t = np.linspace(-1,1,2500)
plt.plot(t,np.hstack((xcorrneg[::-1],xcorrpos)))

plt.subplot(1,2,2)
plt.title('RUN')
stru = {'hpc':13,'BLA':105}
lfp = {}
for s,c in zip(stru.keys(),stru.values()):
    print(s,c)
    lfp.update({s:bk.load.lfp_in_intervals(166,c,theta['run'])})
xcorrpos = pycorrelate.ucorrelate(lfp['hpc'].values,lfp['BLA'].values,maxlag= 1250)
xcorrneg =  pycorrelate.ucorrelate(lfp['BLA'].values,lfp['hpc'].values,maxlag= 1250)
t = np.linspace(-1,1,2500)
plt.plot(t,np.hstack((xcorrneg[::-1],xcorrpos)))

hpc 13
BLA 105
hpc 13
BLA 105


In [78]:
pycorrelate.ucorrelate()

In [60]:
plot_phase_shift(bk.load.path)

Rat : 8 on day : 8
Working with session Rat08-20130716 @ Z:\Rat08\Rat08-20130716
[[1.98656000e+01 4.10112000e+01]
 [7.67232000e+01 1.50656000e+02]
 [1.08150528e+04 1.08215552e+04]
 [1.08300032e+04 1.08359424e+04]
 [1.08429056e+04 1.08484096e+04]
 [1.08558080e+04 1.08647168e+04]
 [1.08689152e+04 1.08727296e+04]
 [1.08786944e+04 1.08826624e+04]
 [1.08919040e+04 1.08943104e+04]
 [1.08983808e+04 1.09020672e+04]
 [1.09026048e+04 1.09062400e+04]
 [1.09072128e+04 1.09154304e+04]
 [1.09442048e+04 1.09468672e+04]
 [1.09581824e+04 1.09612032e+04]
 [1.09660672e+04 1.09687808e+04]
 [1.09700352e+04 1.09764352e+04]
 [1.09875200e+04 1.09896192e+04]
 [1.09903872e+04 1.09948160e+04]
 [1.09955840e+04 1.09987584e+04]
 [1.10075904e+04 1.10141184e+04]
 [1.10195200e+04 1.10245632e+04]
 [1.10388224e+04 1.10410496e+04]
 [1.10441984e+04 1.10498304e+04]
 [1.10531328e+04 1.10557440e+04]
 [1.10654976e+04 1.10692352e+04]
 [1.10773504e+04 1.10795776e+04]
 [1.11025920e+04 1.11049728e+04]
 [1.11083520e+04 1.11129856e

In [50]:
states = bk.load.states()

In [19]:
lfps = bk.load.lfp_in_intervals(166,13,states['Rem'])
filtered = bk.signal.passband(lfps,4,8)
power,phase = bk.signal.hilbert(filtered)
s = plt.subplot(3,1,1)
plt.plot(lfps)
plt.plot(filtered)
plt.subplot(3,1,2,sharex = s)
plt.plot(phase)

In [14]:
f,spec = scipy.signal.welch(lfps,fs = 1250,nperseg=5000,noverlap=4500)

In [16]:
plt.plot(f,np.log(spec))

In [13]:
plt.plot(lfps)

In [31]:
plot_phase_shift(bk.load.path)

Rat : 8 on day : 8
Working with session Rat08-20130716 @ Z:\Rat08\Rat08-20130716
[[1.98656000e+01 4.10112000e+01]
 [7.67232000e+01 1.50656000e+02]
 [1.08150528e+04 1.08215552e+04]
 [1.08300032e+04 1.08359424e+04]
 [1.08429056e+04 1.08484096e+04]
 [1.08558080e+04 1.08647168e+04]
 [1.08689152e+04 1.08727296e+04]
 [1.08786944e+04 1.08826624e+04]
 [1.08919040e+04 1.08943104e+04]
 [1.08983808e+04 1.09020672e+04]
 [1.09026048e+04 1.09062400e+04]
 [1.09072128e+04 1.09154304e+04]
 [1.09442048e+04 1.09468672e+04]
 [1.09581824e+04 1.09612032e+04]
 [1.09660672e+04 1.09687808e+04]
 [1.09700352e+04 1.09764352e+04]
 [1.09875200e+04 1.09896192e+04]
 [1.09903872e+04 1.09948160e+04]
 [1.09955840e+04 1.09987584e+04]
 [1.10075904e+04 1.10141184e+04]
 [1.10195200e+04 1.10245632e+04]
 [1.10388224e+04 1.10410496e+04]
 [1.10441984e+04 1.10498304e+04]
 [1.10531328e+04 1.10557440e+04]
 [1.10654976e+04 1.10692352e+04]
 [1.10773504e+04 1.10795776e+04]
 [1.11025920e+04 1.11049728e+04]
 [1.11083520e+04 1.11129856e

In [8]:
for p in sessions['Path']:
    plot_phase_shift(p)

Rat : 8 on day : 1
Working with session Rat08-20130708 @ Z:\Rat08\Rat08-20130708
[[ 9901.312   9905.5872]
 [ 9906.176   9916.4928]
 [ 9919.5648  9922.7136]
 [ 9929.8048  9936.896 ]
 [ 9943.9872  9949.2608]
 [ 9951.4112  9958.8352]
 [ 9969.024   9983.4624]
 [ 9984.9984  9998.3872]
 [ 9998.8992 10001.7152]
 [10005.4784 10021.9392]
 [10022.5792 10027.52  ]
 [10028.5696 10034.5088]
 [10036.2496 10051.8656]
 [10063.5904 10065.8688]
 [10067.9168 10071.552 ]
 [10075.7504 10088.96  ]
 [10116.3776 10118.7328]
 [10133.1456 10136.2432]
 [10153.0368 10156.16  ]
 [10156.7232 10159.36  ]
 [10165.9392 10169.0368]
 [10176.9984 10182.5024]
 [10198.1184 10200.576 ]
 [10207.8976 10210.2528]
 [10212.0448 10220.9024]
 [10240.0256 10242.4832]
 [10244.224  10254.0544]
 [10300.672  10303.36  ]
 [10305.536  10312.4224]
 [10313.088  10322.7136]
 [10324.3008 10326.4512]
 [10330.3936 10332.8512]
 [10393.7792 10400.2816]
 [10401.2032 10409.2672]
 [10413.2352 10415.6672]
 [10445.696  10461.9264]
 [10465.6384 10471.

FileNotFoundError: [Errno 2] No such file or directory: 'Z:\\Rat08\\Rat08-20130720/States.mat'

In [24]:
np.round(3.22816000e+01,decimals=1)

32.3

In [23]:
np.round(run[:,1],decimals = 1)

TypeError: '(slice(None, None, None), 1)' is an invalid key

In [78]:
32.3*1_000_000

32299999.999999996

In [62]:
np.round(32.2816,decimals=1)

32.3

In [76]:
nts.IntervalSet(0,32300000,time_units='us').as_units('s')

start   end
0    0.0  32.3

In [37]:
bk.load.current_session(path)
states = bk.load.states()
run = scipy.io.loadmat(bk.load.session + '-TrackRunTimes.mat')['trackruntimes']
print(run)
print(np.round(run[:,1],decimals = 1))
run = nts.IntervalSet(np.round(run[:,0],decimals = 1),np.round(run[:,1],decimals = 1),time_units='s')
run = nts.IntervalSet(np.round(run.start,decimals = 1),np.round(run.end,decimals = 1))
print(run.as_units('s'))
theta = {'Rem':states['Rem'],'run':run,'wake':states['wake']}

Rat : 8 on day : 3
Working with session Rat08-20130710 @ Z:\Rat08\Rat08-20130710
[[5.96480000e+00 9.62560000e+00]
 [2.96704000e+01 3.22816000e+01]
 [3.57376000e+01 4.07296000e+01]
 [4.41344000e+01 4.62592000e+01]
 [4.97664000e+01 5.35040000e+01]
 [5.81376000e+01 6.18496000e+01]
 [7.10400000e+01 7.87456000e+01]
 [8.86528000e+01 9.33632000e+01]
 [9.73568000e+01 1.02297600e+02]
 [1.19321600e+02 1.22905600e+02]
 [1.23468800e+02 1.26156800e+02]
 [1.26848000e+02 1.33017600e+02]
 [1.58899200e+02 1.64761600e+02]
 [1.73542400e+02 1.81580800e+02]
 [1.90233600e+02 1.94432000e+02]
 [1.95379200e+02 1.99936000e+02]
 [2.35955200e+02 2.40204800e+02]
 [2.51264000e+02 2.57331200e+02]
 [2.65241600e+02 2.71462400e+02]
 [2.79296000e+02 2.84723200e+02]
 [2.92275200e+02 2.96550400e+02]
 [3.08992000e+02 3.13779200e+02]
 [3.14624000e+02 3.26758400e+02]
 [1.04282624e+04 1.04303104e+04]
 [1.04658176e+04 1.04686336e+04]
 [1.04872704e+04 1.04912384e+04]
 [1.05173248e+04 1.05203968e+04]
 [1.05236992e+04 1.05267456e

In [27]:
bk.load.current_session(path)
states = bk.load.states()
run = scipy.io.loadmat(bk.load.session + '-TrackRunTimes.mat')['trackruntimes']

Rat : 8 on day : 3
Working with session Rat08-20130710 @ Z:\Rat08\Rat08-20130710


In [29]:
path = 'Z:\Rat08\Rat08-20130710'
plot_phase_shift(path)

Rat : 8 on day : 3
Working with session Rat08-20130710 @ Z:\Rat08\Rat08-20130710
[[5.96480000e+00 9.62560000e+00]
 [2.96704000e+01 3.22816000e+01]
 [3.57376000e+01 4.07296000e+01]
 [4.41344000e+01 4.62592000e+01]
 [4.97664000e+01 5.35040000e+01]
 [5.81376000e+01 6.18496000e+01]
 [7.10400000e+01 7.87456000e+01]
 [8.86528000e+01 9.33632000e+01]
 [9.73568000e+01 1.02297600e+02]
 [1.19321600e+02 1.22905600e+02]
 [1.23468800e+02 1.26156800e+02]
 [1.26848000e+02 1.33017600e+02]
 [1.58899200e+02 1.64761600e+02]
 [1.73542400e+02 1.81580800e+02]
 [1.90233600e+02 1.94432000e+02]
 [1.95379200e+02 1.99936000e+02]
 [2.35955200e+02 2.40204800e+02]
 [2.51264000e+02 2.57331200e+02]
 [2.65241600e+02 2.71462400e+02]
 [2.79296000e+02 2.84723200e+02]
 [2.92275200e+02 2.96550400e+02]
 [3.08992000e+02 3.13779200e+02]
 [3.14624000e+02 3.26758400e+02]
 [1.04282624e+04 1.04303104e+04]
 [1.04658176e+04 1.04686336e+04]
 [1.04872704e+04 1.04912384e+04]
 [1.05173248e+04 1.05203968e+04]
 [1.05236992e+04 1.05267456e

ValueError: cannot reshape array of size 761525 into shape (4587,166)

In [11]:
np.round(32.2999999,decimals=1)

32.3

In [21]:
t = np.arange(0,len(lfp_hpc),1)/1250

lfp_bla = bk.load.lfp_in_intervals(172,150,theta['run'])
lfp_hpc= bk.load.lfp_in_intervals(172,65,theta['run'])
plt.figure()
plt.suptitle('Example LFPs during RUN')
s = plt.subplot(2,1,1)
plt.title("Hpc")
plt.plot(t,lfp_hpc.values, c = 'azure',linewidth = 0.5)
plt.plot(t,bk.signal.passband(lfp_hpc,4,8).values,c = 'r')
plt.subplot(2,1,2,sharex=s,sharey = s)
plt.title('BLA')
plt.plot(t,lfp_bla.values, c = 'azure',linewidth = 0.5)
plt.plot(t,bk.signal.passband(lfp_bla,4,8).values,c = 'r')


ValueError: x and y must have same first dimension, but have shapes (12343750,) and (1228750,)

In [9]:
plt.yscale('log')

In [69]:
lfp_hpc = bk.load.lfp_in_intervals(166,23,theta['run'])
filt_hpc = bk.signal.passband(lfp_hpc,4,8)
power_hpc,phase_hpc = bk.signal.hilbert(filt_hpc,deg = True)

ValueError: cannot reshape array of size 497999 into shape (2999,166)

In [82]:
lfp_hpc = bk.load.lfp_in_intervals(172,150,theta['run'])
lfp_bla = bk.load.lfp_in_intervals(172,45,theta['run'])

f,coh = scipy.signal.coherence(lfp_hpc,lfp_bla,fs = 1250,nperseg=5000,noverlap=2500,detrend='linear')
plt.plot(f,coh)

In [80]:
plt.plot(lfp_hpc)
plt.plot(lfp_bla)

In [9]:
lfp_fake = nts.Tsd(lfp_hpc.index.values,np.random.rand(len(lfp_hpc)))
filt_fake = bk.signal.passband(lfp_fake,4,8)
power_fake,phase_fake = bk.signal.hilbert(filt_fake,deg = True)

In [19]:
s = plt.subplot(2,1,1)
plt.plot(lfp_fake.index,lfp_fake.values-np.mean(lfp_fake.values),'azure')
plt.plot(filt_fake,'red')
plt.subplot(2,1,2,sharex = s)
plt.plot(phase_fake)

In [21]:
plt.hist2d(phase_hpc.values+180,phase_fake.values+180,100)
plt.xlabel('hpc_phase')
plt.ylabel('fake_phase')

Text(0, 0.5, 'fake_phase')

In [49]:
t = np.arange(0,3*np.pi,0.1)
y = np.sin(t)
y = nts.Tsd(t,y)

In [50]:
plt.plot(t,y)

In [39]:
a = [0,0,0,0,0,0,0,0]
b = [0,0,0,0,0,0,0,0]

np.corrcoef(a,b)

array([[nan, nan],
       [nan, nan]])