In [ ]:
%matplotlib qt


import os, sys


import pandas as pd
import numpy as np

import scipy.io
import scipy.stats

import matplotlib
import matplotlib.cm as cm
import matplotlib.pyplot as plt

import seaborn as sns

import neuroseries as nts

import basefunction.anass_load as bf
import basefunction.bk_load as bk

import re
import pickle

# Helpers functions

In [ ]:
def intervals_sum(intervals,units = 's'):
    to_sum = []
    for i in intervals.as_units(units).values:
        to_sum.append(np.diff(i))
    return np.sum(to_sum)

In [396]:
path = "Z:\Rat08\Rat08-20130713"


def main(path):
    
    # Initialising variables
    bk.set_current_session(path)
    
    laps = scipy.io.loadmat(bk.session+'-LapType.mat')

    danger_laps = laps['aplaps'][0]['run'][0]
    danger_laps = nts.IntervalSet(danger_laps[:,0],danger_laps[:,1],time_units = 's')

    safe_laps = laps['safelaps'][0]['run'][0]
    safe_laps = nts.IntervalSet(safe_laps[:,0],safe_laps[:,1],time_units = 's')

    laps = {'danger':danger_laps,'safe':safe_laps}

    airpuff = scipy.io.loadmat('airpuff.mat')['airpuff']
    airpuff_loc = scipy.io.loadmat(bk.session + '-PlaceCells.mat')['airP'][0][0]*137
    airpuff_t = nts.Tsd(np.array(pd.read_csv(bk.session+'.puf.evt',sep = '\t',header=None)[0]),time_units='ms')

    pos = bk.load_pos(bk.session)
    # pos_run = pos.restrict(danger_laps).as_units('s')

    # Loading Spikes Data
    
    spks,meta = bk.loadSpikeData(bk.path)
    
    #Computing mean firing rates for each kind of laps for each neurons
    FR = {}
    for laps_type in laps:
        FR.update({laps_type:[]})
        for i,n in enumerate(spks):
            tmp = n.restrict(laps[laps_type])
            fr_tmp = (tmp.times().shape[0])/(intervals_sum(laps[laps_type]))
            FR[laps_type].append(fr_tmp)
    
    # Zip everything in a dataframe
    
    df = pd.DataFrame(zip(meta),columns=['meta'])
    for i in FR:
        a = np.array(FR[i])
        df[i] = FR[i]

    
    safe_fr = np.log(df.safe)
    danger_fr = np.log(df.danger)
    df['log_safe'] = safe_fr
    df['log_danger'] = danger_fr
    
#     df = df.replace([np.inf, -np.inf], np.nan).dropna(how="any")
    return df
    
    
    # Plot
    
    
    pal = sns.cubehelix_palette(2, rot=-.5, dark=.3)

    
#     plt.figure()
#     sns.violinplot(data = df[['log_safe','log_danger']],palette = pal,inner = 'points')
#     plt.title(bk.session)
#     plt.show()
    
    print(scipy.stats.wilcoxon(df['log_safe'],df['log_danger']))
    
df = main('Z:\Rat08\Rat08-20130713')

Rat : 8 on day : 6
Working with session Rat08-20130713 @ Z:\Rat08\Rat08-20130713
Loading Rat08-20130713.clu.1
Loading Rat08-20130713.clu.2
Loading Rat08-20130713.clu.3
Loading Rat08-20130713.clu.4
Loading Rat08-20130713.clu.5
Loading Rat08-20130713.clu.6
Loading Rat08-20130713.clu.7
Loading Rat08-20130713.clu.8
Loading Rat08-20130713.clu.9
Loading Rat08-20130713.clu.10
Loading Rat08-20130713.clu.11
Loading Rat08-20130713.clu.12
Loading Rat08-20130713.clu.13
Loading Rat08-20130713.clu.14
Loading Rat08-20130713.clu.15
Loading Rat08-20130713.clu.16
Loading Rat08-20130713.clu.17
Loading Rat08-20130713.clu.18
Loading Rat08-20130713.clu.19
Loading Rat08-20130713.clu.20


In [409]:
df.replace([-np.inf,np.inf],np.nan).dropna(how = 'any')

print(scipy.stats.wilcoxon(df['log_safe'],df['log_danger']))

WilcoxonResult(statistic=13435.5, pvalue=0.03065584650548224)


C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\morestats.py:2947: RuntimeWarning: invalid value encountered in subtract
  d = x - y


In [4]:
# plt.figure()

# step = 100
# for i in range(0,pos_run.shape[0],2):
#     plt.plot(pos_run['x'].iloc[i:i+step],pos_run['y'].iloc[i:i+step])
#     plt.plot(airpuff_loc,30,'o',color = 'red')
#     plt.title(pos_run.index[i])
#     plt.xlim(25,390)
#     plt.ylim(0,50)
#     plt.pause(0.001)
#     plt.cla()

In [5]:
# hpc_shank = bf.get_structure_shanks(session,'Hpc')

# hpc_mask = []
# for i in meta[:,0]:
#     hpc_mask.append(i in hpc_shank)
# hpc_neurons = spks[hpc_mask]
# meta[hpc_mask]


# bla_shank = bf.get_structure_shanks(session,'BLA')
# bla_mask = []
# for i in meta[:,0]:
#     bla_mask.append(i in bla_shank)
# # spks = spks[bla_mask]
# # meta = meta[bla_mask]

In [10]:
bk.batch(main,verbose = True)

Loading Data from Rat08-20130708
Rat : 8 on day : 1
Working with session Rat08-20130708 @ Z:\Rat08\Rat08-20130708
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat08-20130708.clu.1
Loading Rat08-20130708.clu.2
Loading Rat08-20130708.clu.3
Loading Rat08-20130708.clu.4
Loading Rat08-20130708.clu.5
Loading Rat08-20130708.clu.6
Loading Rat08-20130708.clu.7
Loading Rat08-20130708.clu.8
Loading Rat08-20130708.clu.9
Loading Rat08-20130708.clu.10
Loading Rat08-20130708.clu.11
Loading Rat08-20130708.clu.12
Loading Rat08-20130708.clu.13
Loading Rat08-20130708.clu.14
Loading Rat08-20130708.clu.15
Loading Rat08-20130708.clu.16
Loading Rat08-20130708.clu.17
Loading Rat08-20130708.clu.18
Loading Rat08-20130708.clu.19
Loading Rat08-20130708.clu.20


Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


WilcoxonResult(statistic=3819.0, pvalue=0.8889377307687892)
Loading Data from Rat08-20130709
Rat : 8 on day : 2
Working with session Rat08-20130709 @ Z:\Rat08\Rat08-20130709
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat08-20130709.clu.1
Loading Rat08-20130709.clu.2
Loading Rat08-20130709.clu.3
Loading Rat08-20130709.clu.4
Loading Rat08-20130709.clu.5
Loading Rat08-20130709.clu.6
Loading Rat08-20130709.clu.7
Loading Rat08-20130709.clu.8
Loading Rat08-20130709.clu.9
Loading Rat08-20130709.clu.10
Loading Rat08-20130709.clu.11
Loading Rat08-20130709.clu.12
Loading Rat08-20130709.clu.13
Loading Rat08-20130709.clu.14
Loading Rat08-20130709.clu.15
Loading Rat08-20130709.clu.16
Loading Rat08-20130709.clu.17
Loading Rat08-20130709.clu.18
Loading Rat08-20130709.clu.19
Loading Rat08-20130709.clu.20


Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


WilcoxonResult(statistic=4447.0, pvalue=0.4588958270676018)
Loading Data from Rat08-20130710
Rat : 8 on day : 3
Working with session Rat08-20130710 @ Z:\Rat08\Rat08-20130710
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat08-20130710.clu.1
Loading Rat08-20130710.clu.2
Loading Rat08-20130710.clu.3
Loading Rat08-20130710.clu.4
Loading Rat08-20130710.clu.5
Loading Rat08-20130710.clu.6
Loading Rat08-20130710.clu.7
Loading Rat08-20130710.clu.8
Loading Rat08-20130710.clu.9
Loading Rat08-20130710.clu.10
Loading Rat08-20130710.clu.11
Loading Rat08-20130710.clu.12
Loading Rat08-20130710.clu.13
Loading Rat08-20130710.clu.14
Loading Rat08-20130710.clu.15
Loading Rat08-20130710.clu.16
Loading Rat08-20130710.clu.17
Loading Rat08-20130710.clu.18
Loading Rat08-20130710.clu.19
Loading Rat08-20130710.clu.20


Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


WilcoxonResult(statistic=7224.0, pvalue=0.40472483982307805)
Loading Data from Rat08-20130711
Rat : 8 on day : 4
Working with session Rat08-20130711 @ Z:\Rat08\Rat08-20130711
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat08-20130711.clu.1
Loading Rat08-20130711.clu.2
Loading Rat08-20130711.clu.3
Loading Rat08-20130711.clu.4
Loading Rat08-20130711.clu.5
Loading Rat08-20130711.clu.6
Loading Rat08-20130711.clu.7
Loading Rat08-20130711.clu.8
Loading Rat08-20130711.clu.9
Loading Rat08-20130711.clu.10
Loading Rat08-20130711.clu.11
Loading Rat08-20130711.clu.12
Loading Rat08-20130711.clu.13
Loading Rat08-20130711.clu.14
Loading Rat08-20130711.clu.15
Loading Rat08-20130711.clu.16
Loading Rat08-20130711.clu.17
Loading Rat08-20130711.clu.18
Loading Rat08-20130711.clu.19
Loading Rat08-20130711.clu.20


Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


WilcoxonResult(statistic=7225.0, pvalue=0.6487481175082965)
Loading Data from Rat08-20130712
Rat : 8 on day : 5
Working with session Rat08-20130712 @ Z:\Rat08\Rat08-20130712
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat08-20130712.clu.1
Loading Rat08-20130712.clu.2
Loading Rat08-20130712.clu.3
Loading Rat08-20130712.clu.4
Loading Rat08-20130712.clu.5
Loading Rat08-20130712.clu.6
Loading Rat08-20130712.clu.7
Loading Rat08-20130712.clu.8
Loading Rat08-20130712.clu.9
Loading Rat08-20130712.clu.10
Loading Rat08-20130712.clu.11
Loading Rat08-20130712.clu.12
Loading Rat08-20130712.clu.13
Loading Rat08-20130712.clu.14
Loading Rat08-20130712.clu.15
Loading Rat08-20130712.clu.16
Loading Rat08-20130712.clu.17
Loading Rat08-20130712.clu.18
Loading Rat08-20130712.clu.19
Loading Rat08-20130712.clu.20


Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


WilcoxonResult(statistic=7623.0, pvalue=0.4558638762047398)
Loading Data from Rat08-20130713
Rat : 8 on day : 6
Working with session Rat08-20130713 @ Z:\Rat08\Rat08-20130713
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat08-20130713.clu.1
Loading Rat08-20130713.clu.2
Loading Rat08-20130713.clu.3
Loading Rat08-20130713.clu.4
Loading Rat08-20130713.clu.5
Loading Rat08-20130713.clu.6
Loading Rat08-20130713.clu.7
Loading Rat08-20130713.clu.8
Loading Rat08-20130713.clu.9
Loading Rat08-20130713.clu.10
Loading Rat08-20130713.clu.11
Loading Rat08-20130713.clu.12
Loading Rat08-20130713.clu.13
Loading Rat08-20130713.clu.14
Loading Rat08-20130713.clu.15
Loading Rat08-20130713.clu.16
Loading Rat08-20130713.clu.17
Loading Rat08-20130713.clu.18
Loading Rat08-20130713.clu.19
Loading Rat08-20130713.clu.20


Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


WilcoxonResult(statistic=12717.0, pvalue=0.436106722595317)
Loading Data from Rat08-20130715
Rat : 8 on day : 7
Working with session Rat08-20130715 @ Z:\Rat08\Rat08-20130715
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat08-20130715.clu.1
Loading Rat08-20130715.clu.2
Loading Rat08-20130715.clu.3
Loading Rat08-20130715.clu.4
Loading Rat08-20130715.clu.5
Loading Rat08-20130715.clu.6
Loading Rat08-20130715.clu.7
Loading Rat08-20130715.clu.8
Loading Rat08-20130715.clu.9
Loading Rat08-20130715.clu.10
Loading Rat08-20130715.clu.11
Loading Rat08-20130715.clu.12
Loading Rat08-20130715.clu.13
Loading Rat08-20130715.clu.14
Loading Rat08-20130715.clu.15
Loading Rat08-20130715.clu.16
Loading Rat08-20130715.clu.17
Loading Rat08-20130715.clu.18
Loading Rat08-20130715.clu.19
Loading Rat08-20130715.clu.20


Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


WilcoxonResult(statistic=6486.0, pvalue=0.846841450100954)
Loading Data from Rat08-20130716
Rat : 8 on day : 8
Working with session Rat08-20130716 @ Z:\Rat08\Rat08-20130716
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat08-20130716.clu.1
Loading Rat08-20130716.clu.2
Loading Rat08-20130716.clu.3
Loading Rat08-20130716.clu.4
Loading Rat08-20130716.clu.5
Loading Rat08-20130716.clu.6
Loading Rat08-20130716.clu.7
Loading Rat08-20130716.clu.8
Loading Rat08-20130716.clu.9
Loading Rat08-20130716.clu.10
Loading Rat08-20130716.clu.11
Loading Rat08-20130716.clu.12
Loading Rat08-20130716.clu.13
Loading Rat08-20130716.clu.14
Loading Rat08-20130716.clu.15
Loading Rat08-20130716.clu.16
Loading Rat08-20130716.clu.17
Loading Rat08-20130716.clu.18
Loading Rat08-20130716.clu.19
Loading Rat08-20130716.clu.20


Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


WilcoxonResult(statistic=6630.0, pvalue=0.030451787550978448)
Loading Data from Rat08-20130717
Rat : 8 on day : 9
Working with session Rat08-20130717 @ Z:\Rat08\Rat08-20130717
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat08-20130717.clu.1
Loading Rat08-20130717.clu.2
Loading Rat08-20130717.clu.3
Loading Rat08-20130717.clu.4
Loading Rat08-20130717.clu.5
Loading Rat08-20130717.clu.6
Loading Rat08-20130717.clu.7
Loading Rat08-20130717.clu.8
Loading Rat08-20130717.clu.9
Loading Rat08-20130717.clu.10
Loading Rat08-20130717.clu.11
Loading Rat08-20130717.clu.12
Loading Rat08-20130717.clu.13
Loading Rat08-20130717.clu.14
Loading Rat08-20130717.clu.15
Loading Rat08-20130717.clu.16
Loading Rat08-20130717.clu.17
Loading Rat08-20130717.clu.18
Loading Rat08-20130717.clu.19
Loading Rat08-20130717.clu.20


Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


WilcoxonResult(statistic=8750.0, pvalue=0.6709144903478542)
Loading Data from Rat08-20130718
Rat : 8 on day : 10
Working with session Rat08-20130718 @ Z:\Rat08\Rat08-20130718
Error in session Rat08-20130718
Loading Data from Rat08-20130719
Rat : 8 on day : 11
Working with session Rat08-20130719 @ Z:\Rat08\Rat08-20130719
Error in session Rat08-20130719
Loading Data from Rat08-20130720
Rat : 8 on day : 12
Working with session Rat08-20130720 @ Z:\Rat08\Rat08-20130720
Error in session Rat08-20130720
Loading Data from Rat08-20130722
Rat : 8 on day : 13
Working with session Rat08-20130722 @ Z:\Rat08\Rat08-20130722
Error in session Rat08-20130722
Loading Data from Rat09-20140324


Rat : 9 on day : 1
Working with session Rat09-20140324 @ Z:\Rat09\Rat09-20140324
Error in session Rat09-20140324
Loading Data from Rat09-20140325
Rat : 9 on day : 2
Working with session Rat09-20140325 @ Z:\Rat09\Rat09-20140325
Error in session Rat09-20140325
Loading Data from Rat09-20140326
Rat : 9 on day : 3
Working with session Rat09-20140326 @ Z:\Rat09\Rat09-20140326
Error in session Rat09-20140326
Loading Data from Rat09-20140327
Rat : 9 on day : 4
Working with session Rat09-20140327 @ Z:\Rat09\Rat09-20140327
Error in session Rat09-20140327
Loading Data from Rat09-20140328
Rat : 9 on day : 5
Working with session Rat09-20140328 @ Z:\Rat09\Rat09-20140328
Error in session Rat09-20140328
Loading Data from Rat09-20140329
Rat : 9 on day : 6
Working with session Rat09-20140329 @ Z:\Rat09\Rat09-20140329


Error in session Rat09-20140329
Loading Data from Rat09-20140331
Rat : 9 on day : 7
Working with session Rat09-20140331 @ Z:\Rat09\Rat09-20140331
Error in session Rat09-20140331
Loading Data from Rat09-20140401
Rat : 9 on day : 8
Working with session Rat09-20140401 @ Z:\Rat09\Rat09-20140401
Error in session Rat09-20140401
Loading Data from Rat09-20140402
Rat : 9 on day : 9
Working with session Rat09-20140402 @ Z:\Rat09\Rat09-20140402
Error in session Rat09-20140402
Loading Data from Rat09-20140403
Rat : 9 on day : 10
Working with session Rat09-20140403 @ Z:\Rat09\Rat09-20140403
Error in session Rat09-20140403
Loading Data from Rat09-20140404
Rat : 9 on day : 11
Working with session Rat09-20140404 @ Z:\Rat09\Rat09-20140404


Error in session Rat09-20140404
Loading Data from Rat09-20140405
Rat : 9 on day : 12
Working with session Rat09-20140405 @ Z:\Rat09\Rat09-20140405
Error in session Rat09-20140405
Loading Data from Rat09-20140407
Rat : 9 on day : 13
Working with session Rat09-20140407 @ Z:\Rat09\Rat09-20140407
Error in session Rat09-20140407
Loading Data from Rat09-20140408
Rat : 9 on day : 14
Working with session Rat09-20140408 @ Z:\Rat09\Rat09-20140408
Error in session Rat09-20140408
Loading Data from Rat09-20140409
Rat : 9 on day : 15
Working with session Rat09-20140409 @ Z:\Rat09\Rat09-20140409
Error in session Rat09-20140409
Loading Data from Rat10-20140619
Rat : 10 on day : 1
Working with session Rat10-20140619 @ Z:\Rat10\Rat10-20140619
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat10-20140619.clu.1
Loading Rat10-20140619.clu.2
Loading Rat10-20140619.clu.3
Loading Rat10-20140619.clu.4
Loading Rat10-20140619.cl

Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


WilcoxonResult(statistic=1035.0, pvalue=0.11742621034432427)
Loading Data from Rat10-20140620
Rat : 10 on day : 2
Working with session Rat10-20140620 @ Z:\Rat10\Rat10-20140620
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat10-20140620.clu.1
Loading Rat10-20140620.clu.2
Loading Rat10-20140620.clu.3
Loading Rat10-20140620.clu.4
Loading Rat10-20140620.clu.5
Loading Rat10-20140620.clu.6
Loading Rat10-20140620.clu.7
Loading Rat10-20140620.clu.8
Loading Rat10-20140620.clu.9
Loading Rat10-20140620.clu.10
Loading Rat10-20140620.clu.11
Loading Rat10-20140620.clu.12
Loading Rat10-20140620.clu.13
Loading Rat10-20140620.clu.14
Loading Rat10-20140620.clu.15
Loading Rat10-20140620.clu.16
Loading Rat10-20140620.clu.17
Loading Rat10-20140620.clu.18
Loading Rat10-20140620.clu.19
Loading Rat10-20140620.clu.20


Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


WilcoxonResult(statistic=1348.0, pvalue=0.6842934391086908)
Loading Data from Rat10-20140622
Rat : 10 on day : 3
Working with session Rat10-20140622 @ Z:\Rat10\Rat10-20140622
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat10-20140622.clu.1
Loading Rat10-20140622.clu.2
Loading Rat10-20140622.clu.3
Loading Rat10-20140622.clu.4
Loading Rat10-20140622.clu.5
Loading Rat10-20140622.clu.6
Loading Rat10-20140622.clu.7
Loading Rat10-20140622.clu.8
Loading Rat10-20140622.clu.9
Loading Rat10-20140622.clu.10
Loading Rat10-20140622.clu.11
Loading Rat10-20140622.clu.12
Loading Rat10-20140622.clu.13
Loading Rat10-20140622.clu.14
Loading Rat10-20140622.clu.15
Loading Rat10-20140622.clu.16
Loading Rat10-20140622.clu.17
Loading Rat10-20140622.clu.18
Loading Rat10-20140622.clu.19
Loading Rat10-20140622.clu.20


Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


WilcoxonResult(statistic=2196.0, pvalue=0.060801337809064854)
Loading Data from Rat10-20140624
Rat : 10 on day : 4
Working with session Rat10-20140624 @ Z:\Rat10\Rat10-20140624
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat10-20140624.clu.1
Loading Rat10-20140624.clu.2
Loading Rat10-20140624.clu.3
Loading Rat10-20140624.clu.4
Loading Rat10-20140624.clu.5
Loading Rat10-20140624.clu.6
Loading Rat10-20140624.clu.7
Loading Rat10-20140624.clu.8
Loading Rat10-20140624.clu.9
Loading Rat10-20140624.clu.10
Loading Rat10-20140624.clu.11
Loading Rat10-20140624.clu.12
Loading Rat10-20140624.clu.13
Loading Rat10-20140624.clu.14
Loading Rat10-20140624.clu.15
Loading Rat10-20140624.clu.16
Loading Rat10-20140624.clu.17
Loading Rat10-20140624.clu.18
Loading Rat10-20140624.clu.19
Loading Rat10-20140624.clu.20


Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


WilcoxonResult(statistic=1566.0, pvalue=0.10287415968146363)
Loading Data from Rat10-20140626
Rat : 10 on day : 5
Working with session Rat10-20140626 @ Z:\Rat10\Rat10-20140626
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat10-20140626.clu.1
Loading Rat10-20140626.clu.2
Loading Rat10-20140626.clu.3
Loading Rat10-20140626.clu.4
Loading Rat10-20140626.clu.5
Loading Rat10-20140626.clu.6
Loading Rat10-20140626.clu.7
Loading Rat10-20140626.clu.8
Loading Rat10-20140626.clu.9
Loading Rat10-20140626.clu.10
Loading Rat10-20140626.clu.11
Loading Rat10-20140626.clu.12
Loading Rat10-20140626.clu.13
Loading Rat10-20140626.clu.14
Loading Rat10-20140626.clu.15
Loading Rat10-20140626.clu.16
Loading Rat10-20140626.clu.17
Loading Rat10-20140626.clu.18
Loading Rat10-20140626.clu.19
Loading Rat10-20140626.clu.20


Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


WilcoxonResult(statistic=998.0, pvalue=0.49224674140787017)
Loading Data from Rat10-20140627
Rat : 10 on day : 6
Working with session Rat10-20140627 @ Z:\Rat10\Rat10-20140627
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat10-20140627.clu.1
Loading Rat10-20140627.clu.2
Loading Rat10-20140627.clu.3
Loading Rat10-20140627.clu.4
Loading Rat10-20140627.clu.5
Loading Rat10-20140627.clu.6
Loading Rat10-20140627.clu.7
Loading Rat10-20140627.clu.8
Loading Rat10-20140627.clu.9
Loading Rat10-20140627.clu.10
Loading Rat10-20140627.clu.11
Loading Rat10-20140627.clu.12
Loading Rat10-20140627.clu.13
Loading Rat10-20140627.clu.14
Loading Rat10-20140627.clu.15
Loading Rat10-20140627.clu.16
Loading Rat10-20140627.clu.17
Loading Rat10-20140627.clu.18
Loading Rat10-20140627.clu.19
Loading Rat10-20140627.clu.20


Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


WilcoxonResult(statistic=1149.0, pvalue=0.7265119590722122)
Loading Data from Rat10-20140628
Rat : 10 on day : 7
Working with session Rat10-20140628 @ Z:\Rat10\Rat10-20140628
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat10-20140628.clu.1
Loading Rat10-20140628.clu.2
Loading Rat10-20140628.clu.3
Loading Rat10-20140628.clu.4
Loading Rat10-20140628.clu.5
Loading Rat10-20140628.clu.6
Loading Rat10-20140628.clu.7
Loading Rat10-20140628.clu.8
Loading Rat10-20140628.clu.9
Loading Rat10-20140628.clu.10
Loading Rat10-20140628.clu.11
Loading Rat10-20140628.clu.12
Loading Rat10-20140628.clu.13
Loading Rat10-20140628.clu.14
Loading Rat10-20140628.clu.15
Loading Rat10-20140628.clu.16
Loading Rat10-20140628.clu.17
Loading Rat10-20140628.clu.18
Loading Rat10-20140628.clu.19
Loading Rat10-20140628.clu.20


Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


WilcoxonResult(statistic=573.0, pvalue=8.273101963567386e-09)
Loading Data from Rat10-20140629
Rat : 10 on day : 8
Working with session Rat10-20140629 @ Z:\Rat10\Rat10-20140629
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat10-20140629.clu.1
Loading Rat10-20140629.clu.2
Loading Rat10-20140629.clu.3
Loading Rat10-20140629.clu.4
Loading Rat10-20140629.clu.5
Loading Rat10-20140629.clu.6
Loading Rat10-20140629.clu.7
Loading Rat10-20140629.clu.8
Loading Rat10-20140629.clu.9
Loading Rat10-20140629.clu.10
Loading Rat10-20140629.clu.11
Loading Rat10-20140629.clu.12
Loading Rat10-20140629.clu.13
Loading Rat10-20140629.clu.14
Loading Rat10-20140629.clu.15
Loading Rat10-20140629.clu.16
Loading Rat10-20140629.clu.17
Loading Rat10-20140629.clu.18
Loading Rat10-20140629.clu.19
Loading Rat10-20140629.clu.20


Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


WilcoxonResult(statistic=2168.0, pvalue=0.36151815207303784)
Loading Data from Rat10-20140701
Rat : 10 on day : 9
Working with session Rat10-20140701 @ Z:\Rat10\Rat10-20140701
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat10-20140701.clu.1
Loading Rat10-20140701.clu.2
Loading Rat10-20140701.clu.3
Loading Rat10-20140701.clu.4
Loading Rat10-20140701.clu.5
Loading Rat10-20140701.clu.6
Loading Rat10-20140701.clu.7
Loading Rat10-20140701.clu.8
Loading Rat10-20140701.clu.9
Loading Rat10-20140701.clu.10
Loading Rat10-20140701.clu.11
Loading Rat10-20140701.clu.12
Loading Rat10-20140701.clu.13
Loading Rat10-20140701.clu.14
Loading Rat10-20140701.clu.15
Loading Rat10-20140701.clu.16
Loading Rat10-20140701.clu.17
Loading Rat10-20140701.clu.18
Loading Rat10-20140701.clu.19
Loading Rat10-20140701.clu.20


Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)


WilcoxonResult(statistic=386.0, pvalue=0.7470049080205658)
Loading Data from Rat10-20140702
Rat : 10 on day : 10
Working with session Rat10-20140702 @ Z:\Rat10\Rat10-20140702
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat10-20140702.clu.1
Loading Rat10-20140702.clu.2
Loading Rat10-20140702.clu.3
Loading Rat10-20140702.clu.4
Loading Rat10-20140702.clu.5
Loading Rat10-20140702.clu.6
Loading Rat10-20140702.clu.7
Loading Rat10-20140702.clu.8
Loading Rat10-20140702.clu.9
Loading Rat10-20140702.clu.10
Loading Rat10-20140702.clu.11
Loading Rat10-20140702.clu.12
Loading Rat10-20140702.clu.13
Loading Rat10-20140702.clu.14
Loading Rat10-20140702.clu.15
Loading Rat10-20140702.clu.16
Loading Rat10-20140702.clu.17
Loading Rat10-20140702.clu.18
Loading Rat10-20140702.clu.19
Loading Rat10-20140702.clu.20


Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)


WilcoxonResult(statistic=824.0, pvalue=0.38282266834277046)
Loading Data from Rat10-20140703
Rat : 10 on day : 11
Working with session Rat10-20140703 @ Z:\Rat10\Rat10-20140703
Error in session Rat10-20140703
Loading Data from Rat10-20140704
Rat : 10 on day : 12
Working with session Rat10-20140704 @ Z:\Rat10\Rat10-20140704
Error in session Rat10-20140704
Loading Data from Rat10-20140705
Rat : 10 on day : 13
Working with session Rat10-20140705 @ Z:\Rat10\Rat10-20140705
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat10-20140705.clu.1
Loading Rat10-20140705.clu.2
Loading Rat10-20140705.clu.3
Loading Rat10-20140705.clu.4
Loading Rat10-20140705.clu.5
Loading Rat10-20140705.clu.6
Loading Rat10-20140705.clu.7
Loading Rat10-20140705.clu.8
Loading Rat10-20140705.clu.9
Loading Rat10-20140705.clu.10
Loading Rat10-20140705.clu.11
Loading Rat10-20140705.clu.12
Loading Rat10-20140705.clu.13
Loading Rat10-20140705.

Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:61: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).


WilcoxonResult(statistic=500.0, pvalue=0.4982421741726051)
Loading Data from Rat10-20140707
Rat : 10 on day : 14
Working with session Rat10-20140707 @ Z:\Rat10\Rat10-20140707
Error in session Rat10-20140707
Loading Data from Rat10-20140708
Rat : 10 on day : 15
Working with session Rat10-20140708 @ Z:\Rat10\Rat10-20140708
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat10-20140708.clu.1
Loading Rat10-20140708.clu.2
Loading Rat10-20140708.clu.3
Loading Rat10-20140708.clu.4
Loading Rat10-20140708.clu.5
Loading Rat10-20140708.clu.6
Loading Rat10-20140708.clu.7
Loading Rat10-20140708.clu.8
Loading Rat10-20140708.clu.9
Loading Rat10-20140708.clu.10
Loading Rat10-20140708.clu.11
Loading Rat10-20140708.clu.12
Loading Rat10-20140708.clu.13
Loading Rat10-20140708.clu.14
Loading Rat10-20140708.clu.15
Loading Rat10-20140708.clu.16
Loading Rat10-20140708.clu.17
Loading Rat10-20140708.clu.18
Loading Rat10-20140708

Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:61: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).


WilcoxonResult(statistic=681.0, pvalue=0.5964389439214697)
Loading Data from Rat11-20150310
Rat : 11 on day : 2
Working with session Rat11-20150310 @ Z:\Rat11\Rat11-20150310
Error in session Rat11-20150310
Loading Data from Rat11-20150312
Rat : 11 on day : 3
Working with session Rat11-20150312 @ Z:\Rat11\Rat11-20150312
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat11-20150312.clu.1
Loading Rat11-20150312.clu.2
Loading Rat11-20150312.clu.3
Loading Rat11-20150312.clu.4
Loading Rat11-20150312.clu.5
Loading Rat11-20150312.clu.6
Loading Rat11-20150312.clu.7
Loading Rat11-20150312.clu.8
Loading Rat11-20150312.clu.9
Loading Rat11-20150312.clu.10
Loading Rat11-20150312.clu.11
Loading Rat11-20150312.clu.12
Loading Rat11-20150312.clu.13
Loading Rat11-20150312.clu.14
Loading Rat11-20150312.clu.15
Loading Rat11-20150312.clu.16
Loading Rat11-20150312.clu.17
Loading Rat11-20150312.clu.18
Loading Rat11-20150312.c

Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:61: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).


WilcoxonResult(statistic=1838.0, pvalue=0.3128432872814024)
Loading Data from Rat11-20150313
Rat : 11 on day : 4
Working with session Rat11-20150313 @ Z:\Rat11\Rat11-20150313
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat11-20150313.clu.1
Loading Rat11-20150313.clu.2
Loading Rat11-20150313.clu.3
Loading Rat11-20150313.clu.4
Loading Rat11-20150313.clu.5
Loading Rat11-20150313.clu.6
Loading Rat11-20150313.clu.7
Loading Rat11-20150313.clu.8
Loading Rat11-20150313.clu.9
Loading Rat11-20150313.clu.10
Loading Rat11-20150313.clu.11
Loading Rat11-20150313.clu.12
Loading Rat11-20150313.clu.13
Loading Rat11-20150313.clu.14
Loading Rat11-20150313.clu.15
Loading Rat11-20150313.clu.16
Loading Rat11-20150313.clu.17
Loading Rat11-20150313.clu.18
Loading Rat11-20150313.clu.19
Loading Rat11-20150313.clu.20


Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:61: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).


WilcoxonResult(statistic=3494.0, pvalue=0.217494703321074)
Loading Data from Rat11-20150314
Rat : 11 on day : 5
Working with session Rat11-20150314 @ Z:\Rat11\Rat11-20150314
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat11-20150314.clu.1
Loading Rat11-20150314.clu.2
Loading Rat11-20150314.clu.3
Loading Rat11-20150314.clu.4
Loading Rat11-20150314.clu.5
Loading Rat11-20150314.clu.6
Loading Rat11-20150314.clu.7
Loading Rat11-20150314.clu.8
Loading Rat11-20150314.clu.9
Loading Rat11-20150314.clu.10
Loading Rat11-20150314.clu.11
Loading Rat11-20150314.clu.12
Loading Rat11-20150314.clu.13
Loading Rat11-20150314.clu.14
Loading Rat11-20150314.clu.15
Loading Rat11-20150314.clu.16
Loading Rat11-20150314.clu.17
Loading Rat11-20150314.clu.18
Loading Rat11-20150314.clu.19
Loading Rat11-20150314.clu.20


Z:\Python\Billel\basefunction\bk_load.py:181: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  shank = np.hstack(shank)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:61: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).


WilcoxonResult(statistic=4692.0, pvalue=0.825895301056291)
Loading Data from Rat11-20150315
Rat : 11 on day : 6
Working with session Rat11-20150315 @ Z:\Rat11\Rat11-20150315
Error in session Rat11-20150315
Loading Data from Rat11-20150316
Rat : 11 on day : 7
Working with session Rat11-20150316 @ Z:\Rat11\Rat11-20150316
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Loading Rat11-20150316.clu.1
Loading Rat11-20150316.clu.2
Loading Rat11-20150316.clu.3
Loading Rat11-20150316.clu.4
Loading Rat11-20150316.clu.5
Loading Rat11-20150316.clu.6
Loading Rat11-20150316.clu.7
Loading Rat11-20150316.clu.8
Loading Rat11-20150316.clu.9
Loading Rat11-20150316.clu.10
Loading Rat11-20150316.clu.11
Loading Rat11-20150316.clu.12
Loading Rat11-20150316.clu.13


Error in session Rat11-20150316
Loading Data from Rat11-20150317
Rat : 11 on day : 8
Working with session Rat11-20150317 @ Z:\Rat11\Rat11-20150317
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Error in session Rat11-20150317


KeyboardInterrupt: 

In [7]:
print(scipy.stats.wilcoxon(df['log_safe'],df['log_danger']))

NameError: name 'df' is not defined

In [44]:
pal = sns.cubehelix_palette(2, rot=-.5, dark=.3)

sns.violinplot(data = df[['log_safe','log_danger']],palette = pal,inner = 'points')


In [62]:
np.where(df['safe']==0)

(array([  6,  20,  23,  24,  28,  36,  44,  48,  56,  75,  92, 193, 195,
        198, 204, 216, 217], dtype=int64),)

In [388]:
a = np.random.normal(0,30,50)
b = np.random.normal(0,30,50)

# b[np.random.choice(50,45)] = np.nan

st.rankdata(a,b)

ValueError: unknown method "[ -3.37408718  23.67988845  52.28260955   5.58474959 -15.2404666
 -21.17349896  36.53146158  23.23300141  -3.79908716   8.0300465
 -16.10952108 -20.07867717  38.78780456 -36.89048098  -3.97451738
 -16.51615244  14.60478976 -19.70249076  -4.57780056  20.01441897
   9.91213456 -28.71793492   0.41222274 -10.92882107  42.09971523
  -5.73331413   9.373646    46.19667533   0.40072149  -4.8140443
   8.11854077 -42.33244361 -53.98136809   3.92845755  29.70314074
  29.86403851  22.82096649 -22.46695072  50.67765287 -29.88198242
   2.54419921 -54.83700015 -16.94935294  -2.37456796 -47.90542327
 -47.91213747  18.28843825 -36.08324892 -30.3366669   -9.41713071]"

# np.random.choice(50,2)

In [365]:
np.sort([5, 5 ,2, -np.inf,-np.nan])

array([-inf,   2.,   5.,   5.,  nan])

In [393]:
np.nan - 5

nan