In [2]:
import sys
import itertools

import numpy as np
import pandas as pd
import scipy
from scipy.signal import savgol_filter

import neuroseries as nts

from progressbar import ProgressBar

import time
import matplotlib.pyplot as plt


import seaborn as sns 
import bk.load
import bk.signal
import bk.plot
import importlib; 
importlib.reload(bk.signal)
importlib.reload(bk.plot)
%matplotlib qt
import basefunction.anass_load as at

In [3]:
def thetaMap(lfp,pos):
    filt_lfp = bk.signal

In [4]:
path = bk.load.sessions()['Path'][5]
bk.load.current_session(path)

Rat : 8 on day : 6
Working with session Rat08-20130713 @ Z:\Rat08\Rat08-20130713


True

In [5]:
lfp = bk.load.loadLFP(bk.load.path+ '\\' + bk.load.session+".lfp",166,13)

In [10]:
filtered = bk.signal.passband(lfp,5,9)
xa = scipy.signal.hilbert(filtered)
xa = nts.Tsd(np.array(filtered.index),xa)

array([0.1024, 0.2816, 0.4608, 0.64  , 0.8192, 0.9984, 1.1776, 1.3568,
       1.536 , 1.7152, 1.8944, 2.0736, 2.2528, 2.432 , 2.6112, 2.7904,
       2.9696, 3.1488, 3.328 , 3.5072, 3.6864, 3.8656, 4.0448, 4.224 ,
       4.4032, 4.5824, 4.7616, 4.9408, 5.12  , 5.2992, 5.4784, 5.6576,
       5.8368, 6.016 , 6.1952, 6.3744, 6.5536, 6.7328, 6.912 , 7.0912,
       7.2704, 7.4496, 7.6288, 7.808 , 7.9872, 8.1664, 8.3456, 8.5248,
       8.704 , 8.8832])

In [7]:
x_power = np.abs(xa.values)**2
x_power = nts.Tsd(np.array(filtered.index),x_power)

x_phase = np.angle(xa.values)
x_phase = nts.Tsd(np.array(filtered.index),x_phase)

In [8]:
states = bk.load.states(bk.load.session)

In [18]:
sub = plt.subplot(3,1,1)
plt.plot(lfp.as_units('s')[3200:3400])
plt.plot(filtered.as_units('s')[3200:3400])
bk.plot.intervals(states['Rem'],'orange')
bk.plot.intervals(states['sws'],'grey')
plt.subplot(3,1,2,sharex = sub)
plt.plot(x_power.as_units('s')[3200:3400])
plt.subplot(3,1,3,sharex = sub)
plt.plot(x_phase.as_units('s')[3200:3400])
# bk.plot.intervals(states['Rem'],'orange',time_units='us')
# bk.plot.intervals(states['sws'],'grey',time_units='us')

In [105]:
f,t,Sxx = scipy.signal.spectrogram(lfp.as_units('s'),fs=1250,mode= 'psd',nperseg=2500,noverlap=1250)
mask = (3000<t) & (t<3500)
plt.pcolormesh(t[mask], f, Sxx[:,mask])
plt.clim(0,20000)
plt.ylim(0,80)
plt.ylabel('Frequency [Hz]')
plt.xlabel('Time [sec]')
plt.show()

In [66]:
126562/1250

101.2496

In [32]:
f, Pxx_den = scipy.signal.welch(lfp.restrict(states['sws']), 1250, nperseg=1024)
plt.plot(f, Pxx_den)
plt.xlim(0,100)
plt.xlabel('frequency [Hz]')
plt.ylabel('PSD [V**2/Hz]')
plt.show()

In [58]:
len(t[0:125000])

125000

In [59]:
125000/1250

100.0

In [93]:
Sxx

array([[1.0653145e+00, 8.8852739e+00, 6.2840824e+00, ..., 4.1657593e+01,
        1.0052242e+01, 1.2823708e+01],
       [1.5123276e+01, 6.6955963e+01, 8.6185104e+01, ..., 1.0571002e+02,
        3.5691235e+01, 2.9774002e+01],
       [8.3028778e+01, 5.3204174e+01, 5.4733082e+01, ..., 1.8651159e+01,
        7.5753471e+01, 2.6983379e+01],
       ...,
       [1.9402768e-02, 1.3160699e-02, 1.9652669e-03, ..., 5.5977809e-03,
        2.8745562e-03, 4.8346939e-03],
       [1.2387454e-02, 1.2122419e-02, 9.3830256e-03, ..., 1.2623433e-02,
        5.8417977e-03, 4.0247748e-03],
       [1.1820311e-02, 7.5002401e-03, 4.3947501e-03, ..., 1.0931775e-02,
        3.7404182e-03, 9.3578445e-03]], dtype=float32)

C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\colors.py:263: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  c = np.array(c)


In [88]:
states['sws'].as_units('s')

start      end
0    1448.0   1697.0
1    1777.0   1926.0
2    2104.0   2429.0
3    2826.0   3275.0
4    3383.0   3841.0
5    3888.0   3916.0
6    3970.0   3992.0
7    4024.0   4529.0
8    4568.0   4648.0
9    5044.0   5426.0
10   5489.0   6069.0
11   6368.0   6629.0
12   6970.0   7311.0
13   7375.0   7759.0
14   7788.0   7909.0
15   8485.0   8797.0
16   8887.0   9333.0
17  15516.0  16145.0
18  16436.0  16765.0
19  16801.0  17259.0
20  17364.0  17429.0
21  17497.0  17669.0
22  17689.0  17764.0
23  17791.0  17810.0
24  17852.0  18076.0
25  18132.0  18528.0
26  18663.0  18979.0
27  19086.0  19167.0
28  19187.0  19448.0
29  19546.0  19771.0
30  19818.0  20363.0
31  20867.0  21286.0
32  21359.0  21629.0
33  21675.0  21850.0

In [113]:
v1 = np.random.randint(0,10,5)
sample = np.random.randint(0,50,5)

In [114]:
s = sample[v1 < 4]

In [116]:
s

array([31])