In [1]:
import matplotlib.pyplot as plt
import scipy.io
import scipy.stats
import numpy as np

%matplotlib qt

import itertools

In [2]:
theta_path = "/home/billel/pCloudDrive/IFM/Work/ThetaModAll.mat"
structures_path = '/home/billel/pCloudDrive/IFM/Work/structures.mat'
finalType = '/home/billel/pCloudDrive/IFM/Work/AllRats-FinalType.mat'

In [3]:
thetamod = scipy.io.loadmat(theta_path)
stru = scipy.io.loadmat(structures_path)
finalType = scipy.io.loadmat(finalType)['finalType']

FileNotFoundError: [Errno 2] No such file or directory: '/home/billel/pCloudDrive/IFM/Work/ThetaModAll.mat'

In [4]:
lfps = ['hpc','bla']
structures = ['Hpc','BLA']

In [5]:
plt.figure()
for lfp in lfps:
    r = thetamod['stats'][lfp][0][0]['r'][0][0]
    metadata = thetamod['metadata'][lfp][0][0]
    for structure in structures:
        print(structure + " with theta from " + lfp)

        structure_mask = np.array([np.any(np.all(i == stru[structure],1)) for i in metadata[:,0:3]])
        type_mask = np.array([finalType[np.all(i == finalType[:,0:4],1),4]for i in metadata[:,0:4]]).T == 1
        structure_type_mask = type_mask * structure_mask
        
        print(structure_type_mask.shape)
        n = len(r[:,(type_mask * structure_mask)[0]][0])
        print(n)
        c = scipy.stats.cumfreq(r[:,(structure_mask*type_mask)[0]][0],30)
        x = c.lowerlimit + np.linspace(0, c.binsize*c.cumcount.size,c.cumcount.size)
        plt.plot(x,c.cumcount/n)
legend_list = list(itertools.product(lfps,structures))
print(legend_list[0])
for i,_ in enumerate(legend_list):
    legend_list[i] = "RML of " + legend_list[i][1] + " relative to theta from " + legend_list[i][0]
plt.title('Distribution of RML')
plt.legend(legend_list)

Hpc with theta from hpc
(1, 3999)
770
BLA with theta from hpc
(1, 3999)
1226
Hpc with theta from bla
(1, 4917)
770
BLA with theta from bla
(1, 4917)
1769
('hpc', 'Hpc')


In [84]:
np.array(metadata[:,0:3] == stru['Hpc'])

/home/billel/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


array(False)

In [93]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,2,3,9,7,5,6,8,7])

In [193]:
bla_mask = [np.any(np.all(i == stru[structure],1)) for i in metadata[:,0:3]]

In [370]:
type_mask * structure_mask

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [332]:
type_mask.T

array([[ True,  True, False, ...,  True,  True,  True]])

In [153]:
structure_mask = [np.all(i == stru[structure],1) for i in metadata[:,0:3]]

In [223]:
a = ['b','c']
a[0] = a[0]+"aze"

In [372]:
type_mask

array([[ True],
       [ True],
       [False],
       ...,
       [ True],
       [ True],
       [ True]])

In [238]:
min(r[0])

0.0005913278069331349

In [347]:
type_mask*

array([[False],
       [False],
       [ True],
       ...,
       [False],
       [False],
       [False]])

In [291]:
# for i in metadata[:,0:4]: 
#     print(len(finalType[np.all(i == finalType[:,0:4],1)]))
#     print(finalType[np.all(i == finalType[:,0:4],1)])
#     print(i)

type_mask = np.array([finalType[np.all(i == finalType[:,0:4],1),4]for i in metadata[:,0:4]]) == 1

In [292]:
type_mask

array([[ True],
       [ True],
       [False],
       ...,
       [ True],
       [ True],
       [ True]])

In [387]:
structure_mask = np.array([np.any(np.all(i == stru[structure],1)) for i in metadata[:,0:3]])
type_mask = np.array([finalType[np.all(i == finalType[:,0:4],1),4]for i in metadata[:,0:4]]) == 2
        

In [388]:
a = structure_mask

In [389]:
b = type_mask.squeeze()

In [390]:
a*b

array([False, False, False, ..., False, False, False])

Text(0.5, 1.0, 'Distribution of RML Pyr')

In [6]:
?np.save

Signature: np.save(file, arr, allow_pickle=True, fix_imports=True)
Docstring:
Save an array to a binary file in NumPy ``.npy`` format.

Parameters
----------
file : file, str, or pathlib.Path
    File or filename to which the data is saved.  If file is a file-object,
    then the filename is unchanged.  If file is a string or Path, a ``.npy``
    extension will be appended to the filename if it does not already
    have one.
arr : array_like
    Array data to be saved.
allow_pickle : bool, optional
    Allow saving object arrays using Python pickles. Reasons for disallowing
    pickles include security (loading pickled data can execute arbitrary
    code) and portability (pickled objects may not be loadable on different
    Python installations, for example if the stored objects require libraries
    that are not available, and not all pickled data is compatible between
    Python 2 and Python 3).
    Default: True
fix_imports : bool, optional
    Only useful in forcing objects in obje